server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_donation
    username: root
    password: root
  jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect